apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastlane-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastlane-api
  template:
    metadata:
      labels:
        app: fastlane-api
    spec:
      containers:
      - name: api
        image: fastlane-api:latest
        ports:
        - containerPort: 80
